import Head from "next/head";
import Image from "next/image";
import Header from "@components/Header";

export default function Base(props) {
    return (
        <div id="clb-layout">
            <Head>
                <title>CLB Yazılım</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header actions={props.actions}/>

            <main className="main">{props.children}</main>
        </div>
    );
}
